#!/usr/bin/env bash
# Starts the whole portal on http://localhost:3000 with the Stage 1 local
# stand-ins (architecture §4.7). The only prerequisite is Node.js 24 LTS.
set -euo pipefail
cd "$(dirname "$0")/.."

major="$(node -p 'process.versions.node.split(".")[0]' 2>/dev/null || echo none)"
if [ "$major" != "24" ]; then
  echo "The portal needs Node.js 24 LTS; found: $(node --version 2>/dev/null || echo 'no node')." >&2
  echo "Install it with: nvm install 24 && nvm use 24" >&2
  exit 1
fi

[ -d node_modules ] || npm ci
mkdir -p .local
if [ ! -f .env.local ]; then
  cat > .env.local <<'ENV'
# Generated by scripts/dev.sh. Local stand-ins only; no real secret belongs here.
PORTAL_MODE=local
PORTAL_PUBLIC_URL=http://localhost:3000
SIGN_IN_ADAPTER=local
DATABASE_ADAPTER=local
EMAIL_ADAPTER=local
CLOCK_ADAPTER=local
DATABASE_FILE=.local/portal.db
ENV
fi
set -a; . ./.env.local; set +a
# Absolute, because npm runs workspace scripts from the workspace directory.
export DATABASE_FILE="$PWD/${DATABASE_FILE:-.local/portal.db}"
export WEB_DIST_DIR="$PWD/apps/web/dist"

if [ ! -f "$DATABASE_FILE" ]; then
  echo "No local database: creating it from seed data."
  npm run seed --workspace apps/server --silent
fi
[ -f seed/sample-erp.xlsx ] || npm run seed:sample-erp --silent
npm run build:local --workspace apps/web --silent
exec npm run dev --workspace apps/server --silent
